---
- name: Install Postgres
  apt: name='{{ item }}' update_cache=yes state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Destroy Borgia database
  become : yes
  become_user: postgres
  postgresql_db:
    name: '{{ db_name }}'
    state: absent

- name: Create Borgia database
  become : yes
  become_user: postgres
  postgresql_db:
    name: '{{ db_name }}'
    encoding: UTF-8
    template: template0

- name: Generating random password for Borgia DB user
  become: yes
  shell: "< /dev/urandom tr -dc _A-Za-z0-9 | head -c12"
  register: db_password

- name: Create Borgia user
  become_user: postgres
  postgresql_user:
    name: '{{ db_user }}'
    password: '{{ db_password.stdout }}'
    db: '{{ db_name }}'
    priv: "ALL"

